"""Gemini API client — translation only.

The counselor response is now generated by the CrewAI agent (crew/crew.py)
which uses the LiteLLM/CrewAI LLM integration directly.

This module retains a single function:
  translate_text — Tamil / Tanglish → English, with L4 cache.
"""

import asyncio
from google import genai
from server.config import (
    GEMINI_API_KEY, GEMINI_MODEL, MAX_OUTPUT_TOKENS,
)
from server.cache.l4_translation import l4_cache

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = genai.Client(api_key=GEMINI_API_KEY)
    return _client


async def translate_text(text: str, source_lang: str, target_lang: str) -> str:
    """Translate Tamil or Tanglish to English using Gemini (L4 cached).

    Args:
        text:        Source text to translate.
        source_lang: 'ta' (pure Tamil) or 'tanglish'.
        target_lang: Always 'en' in current usage.

    Returns:
        Translated text, or the original text if translation fails.
    """
    lang_pair = f"{source_lang}→{target_lang}"
    cached = await l4_cache.get(text, lang_pair)
    if cached:
        return cached

    client = _get_client()
    lang_names = {"en": "English", "ta": "Tamil", "tanglish": "Tanglish"}

    if source_lang == "tanglish":
        prompt = f"""Convert the following Tanglish text to natural English.
Tanglish is romanized Tamil mixed with English, commonly spoken by Chennai college students.
Examples:
- "namma college la placement semma da" → "The placements at our college are excellent"
- "fee evlo aagum bro" → "How much will the fee be"
- "hostel room nalla irukka" → "Is the hostel room good"
Preserve all proper nouns, course names (B.Tech, M.Tech, etc.), numbers, college names, and acronyms exactly as-is.
Only output the English translation, nothing else.

Text: {text}"""
    else:
        prompt = f"""Translate the following text from {lang_names.get(source_lang, source_lang)} to {lang_names.get(target_lang, target_lang)}.
Preserve all proper nouns, course names (B.Tech, M.Tech, etc.), numbers, URLs, and acronyms exactly as-is.
Only output the translation, nothing else.

Text: {text}"""

    try:
        response = await asyncio.to_thread(
            client.models.generate_content,
            model=GEMINI_MODEL,
            contents=prompt,
            config=genai.types.GenerateContentConfig(
                temperature=0.1,
                max_output_tokens=MAX_OUTPUT_TOKENS,
            ),
        )
        result = response.text
        await l4_cache.put(text, lang_pair, result)
        return result
    except Exception:
        return text
